### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by Wilton-Dsouza**
added footer
#6 

Screenshot (14)

### CODE REVIEW

**Comment by WinstonPais** [comment]
@Wilton-Dsouza  Add alt prop to all images.
this should be able to successfully build it.

**Review by WinstonPais — CHANGES_REQUESTED** [review]
@Wilton-Dsouza could you make the row of pictures horizontally scrollable.
Also it would be better if you could split it into 2 different components. with the top component taking a list a images.

**Comment by Wilton-Dsouza** [comment]
added footer
#6

**Comment by Wilton-Dsouza** [comment]
added footer
#6 
Screenshot (16)

**Review by WinstonPais — APPROVED** [review]

**Review by vinstenleon — APPROVED** [review]

**Pull request merged**
